## Numpy
Numpy is a fundamental liberary for scientific computing in python

In [10]:
## create array using numpy
## create a 1D array
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [9]:
## 2d array

arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1+arr2)
print(arr1-arr2)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
